#!/usr/bin/env python3

import os, sys
from PyQt5.QtCore import QObject
from PyQt5.QtQml import QQmlApplicationEngine, qmlRegisterType  # sudo pkg install py37-qt5-qml
from PyQt5.QtGui import QIcon, QGuiApplication

class Wizard(QObject):
    def __init__(self, arg):
        print("Hello from within Python")
        print(sender)

def runQML(self):
    app = QGuiApplication(sys.argv)
    qmlRegisterType(Wizard, 'Service', 1, 0, 'Wizard')
    engine = QQmlApplicationEngine()
    app.setWindowIcon(QIcon(os.path.dirname(__file__) + '/Resources/Welcome.png'))
    engine.load(os.path.dirname(__file__) + '/Resources/main.qml')
 
    if not engine.rootObjects():
        return -1
 
    return app.exec_()
    
 
if __name__ == "__main__":
    sys.exit(runQML())
