# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog_kill_process.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KillDialog(object):
    def setupUi(self, KillDialog):
        KillDialog.setObjectName("KillDialog")
        KillDialog.resize(440, 147)
        self.verticalLayout = QtWidgets.QVBoxLayout(KillDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainVbox = QtWidgets.QVBoxLayout()
        self.MainVbox.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainVbox.setContentsMargins(0, 0, 0, 0)
        self.MainVbox.setSpacing(6)
        self.MainVbox.setObjectName("MainVbox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon = QtWidgets.QLabel(KillDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMinimumSize(QtCore.QSize(64, 64))
        self.icon.setMaximumSize(QtCore.QSize(64, 64))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/Processes.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout_2.addWidget(self.icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(KillDialog)
        self.title.setStyleSheet("QLabel {\n"
                                 "    font: bold\n"
                                 "}")
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.text = QtWidgets.QLabel(KillDialog)
        self.text.setObjectName("text")
        self.verticalLayout_2.addWidget(self.text)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.MainVbox.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        self.MainVbox.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_cancel = QtWidgets.QPushButton(KillDialog)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_force_quit = QtWidgets.QPushButton(KillDialog)
        self.button_force_quit.setObjectName("button_force_quit")
        self.horizontalLayout.addWidget(self.button_force_quit)
        self.button_quit = QtWidgets.QPushButton(KillDialog)
        self.button_quit.setObjectName("button_quit")
        self.horizontalLayout.addWidget(self.button_quit)
        self.MainVbox.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.MainVbox)

        self.retranslateUi(KillDialog)
        QtCore.QMetaObject.connectSlotsByName(KillDialog)

    def retranslateUi(self, KillDialog):
        _translate = QtCore.QCoreApplication.translate
        KillDialog.setWindowTitle(_translate("KillDialog", "Dialog"))
        self.title.setText(_translate("KillDialog", "TextLabel"))
        self.text.setText(_translate("KillDialog", "TextLabel"))
        self.button_cancel.setText(_translate("KillDialog", "Cancel"))
        self.button_force_quit.setText(_translate("KillDialog", "Force Quit"))
        self.button_quit.setText(_translate("KillDialog", "Quit"))


import qressources_rc
