# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dialog_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(297, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(0, 0))
        AboutDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout_2.setContentsMargins(13, 13, 13, 13)
        self.verticalLayout_2.setSpacing(13)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.about_verticalLayout = QtWidgets.QVBoxLayout()
        self.about_verticalLayout.setObjectName("about_verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.about_verticalLayout.addItem(spacerItem)
        self.about_logo = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_logo.sizePolicy().hasHeightForWidth())
        self.about_logo.setSizePolicy(sizePolicy)
        self.about_logo.setMinimumSize(QtCore.QSize(64, 64))
        self.about_logo.setMaximumSize(QtCore.QSize(64, 64))
        self.about_logo.setBaseSize(QtCore.QSize(0, 0))
        self.about_logo.setText("")
        self.about_logo.setPixmap(QtGui.QPixmap(":/Processes.png"))
        self.about_logo.setScaledContents(True)
        self.about_logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.about_logo.setObjectName("about_logo")
        self.about_verticalLayout.addWidget(self.about_logo, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.about_verticalLayout.addItem(spacerItem1)
        self.about_app_name = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.about_app_name.setFont(font)
        self.about_app_name.setWordWrap(False)
        self.about_app_name.setObjectName("about_app_name")
        self.about_verticalLayout.addWidget(self.about_app_name)
        self.about_version = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.about_version.setFont(font)
        self.about_version.setWordWrap(True)
        self.about_version.setObjectName("about_version")
        self.about_verticalLayout.addWidget(self.about_version)
        self.about_text = QtWidgets.QLabel(AboutDialog)
        self.about_text.setTextFormat(QtCore.Qt.AutoText)
        self.about_text.setWordWrap(True)
        self.about_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.about_text.setObjectName("about_text")
        self.about_verticalLayout.addWidget(self.about_text)
        self.about_footer = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.about_footer.setFont(font)
        self.about_footer.setWordWrap(True)
        self.about_footer.setObjectName("about_footer")
        self.about_verticalLayout.addWidget(self.about_footer)
        self.verticalLayout_2.addLayout(self.about_verticalLayout)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", " "))
        self.about_app_name.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\"\n"
"         font-size:16pt;\">Activity Monitor</span></p></body></html>\n"
"        "))
        self.about_version.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\"\n"
"         font-size:10pt; color:#241f31;\">Version 0.1a</span></p></body></html>\n"
"        "))
        self.about_text.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\">This project is open souce,\n"
"         contributions are welcomed.</p><p align=\"center\">Visit <a href=\"https://github.com/helloSystem/Utilities/\"><span\n"
"         style=\" text-decoration: underline; color:#0000ff;\">https://github.com/helloSystem/Utilities/</span></a>\n"
"         for more information or to report bug and/or suggest a new feature.</p></body></html>\n"
"        "))
        self.about_footer.setText(_translate("AboutDialog", "<html><head/><body><p align=\"center\"><span style=\"\n"
"         font-size:10pt; color:#3d3846;\">Copyright 2023-2024 helloSystem Team. All right reserved.</span></p></body></html>\n"
"        "))
import qressources_rc
