#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
SUDO_ASKPASS="/usr/local/bin/askpass" exec "${HERE}/Resources/hardware-probe.py" "$@"
# SUDO_ASKPASS="${HERE}/Resources/askpass.py" exec sudo -A -E "${HERE}/Resources/hardware-probe.py" "$@"
