# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './tab_network.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabNetwork(object):
    def setupUi(self, TabNetwork):
        TabNetwork.setObjectName("TabNetwork")
        TabNetwork.resize(777, 378)
        TabNetwork.setLayoutDirection(QtCore.Qt.LeftToRight)
        TabNetwork.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TabNetwork)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_packets_out_sec = QtWidgets.QLabel(TabNetwork)
        self.label_packets_out_sec.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_out_sec.setObjectName("label_packets_out_sec")
        self.gridLayout.addWidget(self.label_packets_out_sec, 3, 0, 1, 1)
        self.label_data_sent = QtWidgets.QLabel(TabNetwork)
        self.label_data_sent.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_sent.setObjectName("label_data_sent")
        self.gridLayout.addWidget(self.label_data_sent, 1, 3, 1, 1)
        self.label_bandwidth_value = QtWidgets.QLabel(TabNetwork)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bandwidth_value.sizePolicy().hasHeightForWidth())
        self.label_bandwidth_value.setSizePolicy(sizePolicy)
        self.label_bandwidth_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bandwidth_value.setObjectName("label_bandwidth_value")
        self.gridLayout.addWidget(self.label_bandwidth_value, 0, 6, 1, 1,
                                  QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.label_data_sent_value = QtWidgets.QLabel(TabNetwork)
        self.label_data_sent_value.setText("")
        self.label_data_sent_value.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_sent_value.setObjectName("label_data_sent_value")
        self.gridLayout.addWidget(self.label_data_sent_value, 1, 4, 1, 1)
        self.label_packets_out = QtWidgets.QLabel(TabNetwork)
        self.label_packets_out.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_out.setObjectName("label_packets_out")
        self.gridLayout.addWidget(self.label_packets_out, 1, 0, 1, 1)
        self.label_packets_in_sec_value = QtWidgets.QLabel(TabNetwork)
        self.label_packets_in_sec_value.setText("")
        self.label_packets_in_sec_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_in_sec_value.setObjectName("label_packets_in_sec_value")
        self.gridLayout.addWidget(self.label_packets_in_sec_value, 2, 1, 1, 1)
        self.label_packets_in_value = QtWidgets.QLabel(TabNetwork)
        self.label_packets_in_value.setText("")
        self.label_packets_in_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_in_value.setObjectName("label_packets_in_value")
        self.gridLayout.addWidget(self.label_packets_in_value, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.label_packets_in_sec = QtWidgets.QLabel(TabNetwork)
        self.label_packets_in_sec.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_in_sec.setObjectName("label_packets_in_sec")
        self.gridLayout.addWidget(self.label_packets_in_sec, 2, 0, 1, 1)
        self.label_data_received_value = QtWidgets.QLabel(TabNetwork)
        self.label_data_received_value.setText("")
        self.label_data_received_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_received_value.setObjectName("label_data_received_value")
        self.gridLayout.addWidget(self.label_data_received_value, 0, 4, 1, 1)
        self.label_data_received = QtWidgets.QLabel(TabNetwork)
        self.label_data_received.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_received.setObjectName("label_data_received")
        self.gridLayout.addWidget(self.label_data_received, 0, 3, 1, 1)
        self.label_packets_out_value = QtWidgets.QLabel(TabNetwork)
        self.label_packets_out_value.setText("")
        self.label_packets_out_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_out_value.setObjectName("label_packets_out_value")
        self.gridLayout.addWidget(self.label_packets_out_value, 1, 1, 1, 1)
        self.label_data_sent_sec_value = QtWidgets.QLabel(TabNetwork)
        self.label_data_sent_sec_value.setText("")
        self.label_data_sent_sec_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_sent_sec_value.setObjectName("label_data_sent_sec_value")
        self.gridLayout.addWidget(self.label_data_sent_sec_value, 3, 4, 1, 1)
        self.color_picker_data_received_sec_value = ColorButton(TabNetwork)
        self.color_picker_data_received_sec_value.setObjectName("color_picker_data_received_sec_value")
        self.gridLayout.addWidget(self.color_picker_data_received_sec_value, 2, 5, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.color_picker_data_sent_sec_value = ColorButton(TabNetwork)
        self.color_picker_data_sent_sec_value.setObjectName("color_picker_data_sent_sec_value")
        self.gridLayout.addWidget(self.color_picker_data_sent_sec_value, 3, 5, 1, 1, QtCore.Qt.AlignLeft)
        self.label_data_received_sec_value = QtWidgets.QLabel(TabNetwork)
        self.label_data_received_sec_value.setText("")
        self.label_data_received_sec_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_received_sec_value.setObjectName("label_data_received_sec_value")
        self.gridLayout.addWidget(self.label_data_received_sec_value, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        self.label_packets_in = QtWidgets.QLabel(TabNetwork)
        self.label_packets_in.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_in.setObjectName("label_packets_in")
        self.gridLayout.addWidget(self.label_packets_in, 0, 0, 1, 1)
        self.label_data_received_sec = QtWidgets.QLabel(TabNetwork)
        self.label_data_received_sec.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_received_sec.setObjectName("label_data_received_sec")
        self.gridLayout.addWidget(self.label_data_received_sec, 2, 3, 1, 1)
        self.label_data_sent_sec = QtWidgets.QLabel(TabNetwork)
        self.label_data_sent_sec.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_data_sent_sec.setObjectName("label_data_sent_sec")
        self.gridLayout.addWidget(self.label_data_sent_sec, 3, 3, 1, 1)
        self.label_packets_out_sec_value = QtWidgets.QLabel(TabNetwork)
        self.label_packets_out_sec_value.setText("")
        self.label_packets_out_sec_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_packets_out_sec_value.setObjectName("label_packets_out_sec_value")
        self.gridLayout.addWidget(self.label_packets_out_sec_value, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TabNetwork)
        QtCore.QMetaObject.connectSlotsByName(TabNetwork)

    def retranslateUi(self, TabNetwork):
        _translate = QtCore.QCoreApplication.translate
        TabNetwork.setWindowTitle(_translate("TabNetwork", "Form"))
        self.label_packets_out_sec.setText(_translate("TabNetwork", "Packets out/sec:"))
        self.label_data_sent.setText(_translate("TabNetwork", "Data sent:"))
        self.label_bandwidth_value.setText(_translate("TabNetwork", "TextLabel"))
        self.label_packets_out.setText(_translate("TabNetwork", "Packets out:"))
        self.label_packets_in_sec.setText(_translate("TabNetwork", "Packets in/sec:"))
        self.label_data_received.setText(_translate("TabNetwork", "Data received:"))
        self.label_packets_in.setText(_translate("TabNetwork", "Packets in:"))
        self.label_data_received_sec.setText(_translate("TabNetwork", "Data received/sec:"))
        self.label_data_sent_sec.setText(_translate("TabNetwork", "Data sent/sec:"))


from .widget_color_pickup import ColorButton
