# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './tab_disk_usage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabDiskUsage(object):
    def setupUi(self, TabDiskUsage):
        TabDiskUsage.setObjectName("TabDiskUsage")
        TabDiskUsage.resize(904, 212)
        TabDiskUsage.setLayoutDirection(QtCore.Qt.LeftToRight)
        TabDiskUsage.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TabDiskUsage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_space_utilized = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_utilized.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_utilized.setObjectName("label_space_utilized")
        self.gridLayout.addWidget(self.label_space_utilized, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.color_button_space_free = ColorButton(TabDiskUsage)
        self.color_button_space_free.setObjectName("color_button_space_free")
        self.gridLayout.addWidget(self.color_button_space_free, 3, 6, 1, 1, QtCore.Qt.AlignLeft)
        self.label_space_utilized_value_in_bytes = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_utilized_value_in_bytes.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_utilized_value_in_bytes.setObjectName("label_space_utilized_value_in_bytes")
        self.gridLayout.addWidget(self.label_space_utilized_value_in_bytes, 2, 5, 1, 1)
        self.combobox_devices = QtWidgets.QComboBox(TabDiskUsage)
        self.combobox_devices.setObjectName("combobox_devices")
        self.gridLayout.addWidget(self.combobox_devices, 0, 1, 1, 4)
        self.label_space_total_value = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_total_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_space_total_value.setObjectName("label_space_total_value")
        self.gridLayout.addWidget(self.label_space_total_value, 3, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.color_button_space_utilized = ColorButton(TabDiskUsage)
        self.color_button_space_utilized.setObjectName("color_button_space_utilized")
        self.gridLayout.addWidget(self.color_button_space_utilized, 2, 6, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
        self.label_space_free_value = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_free_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_free_value.setObjectName("label_space_free_value")
        self.gridLayout.addWidget(self.label_space_free_value, 3, 3, 1, 1)
        self.label_space_free_value_in_bytes = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_free_value_in_bytes.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_free_value_in_bytes.setObjectName("label_space_free_value_in_bytes")
        self.gridLayout.addWidget(self.label_space_free_value_in_bytes, 3, 5, 1, 1)
        self.label_space_free = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_free.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_free.setObjectName("label_space_free")
        self.gridLayout.addWidget(self.label_space_free, 3, 1, 1, 1)
        self.label_space_utilized_value = QtWidgets.QLabel(TabDiskUsage)
        self.label_space_utilized_value.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_space_utilized_value.setObjectName("label_space_utilized_value")
        self.gridLayout.addWidget(self.label_space_utilized_value, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 8, 1, 1)
        self.chart_pie = ChartPie(TabDiskUsage)
        self.chart_pie.setObjectName("chart_pie")
        self.gridLayout.addWidget(self.chart_pie, 0, 7, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(TabDiskUsage)
        QtCore.QMetaObject.connectSlotsByName(TabDiskUsage)

    def retranslateUi(self, TabDiskUsage):
        _translate = QtCore.QCoreApplication.translate
        TabDiskUsage.setWindowTitle(_translate("TabDiskUsage", "Form"))
        self.label_space_utilized.setText(_translate("TabDiskUsage", "Space utilized:"))
        self.label_space_utilized_value_in_bytes.setText(_translate("TabDiskUsage", "TextLabel"))
        self.label_space_total_value.setText(_translate("TabDiskUsage", "TextLabel"))
        self.label_space_free_value.setText(_translate("TabDiskUsage", "TextLabel"))
        self.label_space_free_value_in_bytes.setText(_translate("TabDiskUsage", "TextLabel"))
        self.label_space_free.setText(_translate("TabDiskUsage", "Space free:"))
        self.label_space_utilized_value.setText(_translate("TabDiskUsage", "TextLabel"))
from .widget_chartpie import ChartPie
from .widget_color_pickup import ColorButton
